### ISSUE TITLE
Unable to Upload Profile Image

### ISSUE THREAD

**Issue by Gloriean** [rotimi-best/classroomio#100]
### Issue Description

Users are encountering issues when attempting to upload a profile image. The upload process is not functioning as expected.

https://jam.dev/c/486dd893-382b-4ce0-b44e-923863e996b8

<img width="1668" alt="Screenshot 2023-12-12 at 12 13 37" src="https://github.com/rotimi-best/classroomio/assets/99972504/c31ccec6-74aa-4816-b525-4e0b0768bc51">

<img width="1680" alt="Screenshot 2023-12-12 at 12 14 42" src="https://github.com/rotimi-best/classroomio/assets/99972504/ba2b0dc5-ca0d-48f4-8d59-4f02f8e549e8">

<img width="1107" alt="Screenshot 2023-12-12 at 12 22 38" src="https://github.com/rotimi-best/classroomio/assets/99972504/8cbd09ef-07b1-4a09-bad0-c8e20ee72394">

### Steps to Reproduce

1. Log in to the application.
2. Navigate to the profile settings.
3. Click on the "Upload Profile Image" button.
4. Select an image from the local storage.
5. Observe the behavior.

### Expected Behavior

The selected image should be successfully uploaded, and users' profile images should be updated accordingly.

### Current Behavior

The image upload process fails, and the selected image is not reflected in the user's profile. Users didn't receive an error message indicating the unsuccessful upload. It's displaying a broken image.

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Gloriean** [comment]
Provide a suitable error message in case the image type is not acceptable.

**Comment by tioluwani94** [comment]
Hi, @Gloriean I think this has been fixed, I tested and I was able to upload a profile picture as well as an organization image. Except if the error occurs when trying to upload an image with a specific format, if that's the case stating the image format that's cause the functionality to break will be helpful.

**Comment by rotimi-best** [comment]
@tioluwani94 Thank you very much for confirming as well.

I have just tested this and it works fine for me too, maybe it was a network issue on your end.

https://jam.dev/c/68e8f119-0f31-4f5f-8034-2c8cb74fe1a4

**Comment by rotimi-best** [comment]
I will be closing it for the main time, @Gloriean if you think this issue still exists, do reopen it.

Thanks 😊

**Comment by Gloriean** [comment]
I'm sorry to close, it's functioning properly as expected.

**Comment by rotimi-best** [comment]
Thanks for confirming smile 😃  @Gloriean
