### ISSUE TITLE
The Color contrast in the FAQ section of the website is low. Problem with Accessibility.  

### ISSUE THREAD

**Issue by emilychima** [rotimi-best/classroomio#103]
### Improvement Description

Reading the responses to the questions in the FAQ section of the website will cause users to strain their eyes. This is because a light shade of grey was used in the answers and reading is difficult as a result of the white background. 

![Screenshot_20231213-200309_1](https://github.com/rotimi-best/classroomio/assets/122826869/54b689a9-6759-4e6e-bf89-68187810c952)
See image above. 

### Rationale

Designing for all users is very important for user centered design  Accessibility is an important aspect of UX, accessibility ensures that all groups of people/users are able to use your product. Readability is an important aspect of accessibility, it ensures that people with eye disabilities can properly use your product. 
For a user with eye disability or even users without any disability, reading the FAQ section will cause them to strain their eyes and as a result they will be thrown off.  

### Proposed Solution

My proposed solution is that a darker shade of grey be used as the color for the responses/answers. This ensures that the answers are easily readable and legible. The FAQ section is pointless if users are unable to read the answers to said questions. See image below for possible solutions 
![Screenshot_20231213-200349_1](https://github.com/rotimi-best/classroomio/assets/122826869/18d9e57b-ec58-46a9-bceb-de89ceec20b2)

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
@emilychima Thank you for reporting this issue.

Our amazing @Chifez just fixed it with this PR: https://github.com/rotimi-best/classroomio/pull/106
