### ISSUE TITLE
Populate Supabase seed.sql with dummy data

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#104]
### Feature Description

The dummy data should contain the following:

1. Admin account: 
  - Email: admin@test.com
  - Password: 123456
  - Full name: Elon Gates
 
2. Organization:
  - Name: Udemy Test
  - Sitename: udemy-test

3. Create 3 courses in this organisation, please make sure the courses meet the following criteria:
  - Each should have 5 lessons
  - Add a youtube video
  - Add some comments
  - Create 1 exercise for each lesson
  - Publish all courses
  - Note: please let each of the content be as realistic as possible

### Student dashboard.

Follow the [guide here](https://www.classroomio.com/docs/contributor-guides/student-dashboard) to set up a student dashboard

1.  Create an account as a student
  - Email: student@test.com
  - Password: 123456
  - Full name: John Doe
 
2. Sign up for only 1 course

3. Go to the course and mark 2 lessons as complete

4. Submit 2 exercises 

### Use Case

This is helpful so that when someone starts the project, they can already see real data

### Proposed Solution

The easiest way to implement this task is to use the dashboard to create all the content as specified above, then run a supabase or Postgres command to dump all data  in the db into the seed.sql file.

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
@cannarron Here is the task. Please let me know if you find anything confusing.

Thanks

**Comment by cannarron** [comment]
Okay @rotimi-best
