### ISSUE TITLE
Monthly and annual pricing option button

### ISSUE THREAD

**Issue by rahbhee** [rotimi-best/classroomio#105]
### Improvement Description

For better UI and UX, I suggest a hover effect for the button that displays "save 2 months"

### Rationale

It would provide a better user interface and user experience.
"Attempting to click on the text 'Save 2 months' became a pain point for me because I initially perceived it as a clickable button."

### Proposed Solution

"Please implement a hover effect on the 'annually' option that displays the text in a smaller div or any other HTML tag chosen by the developer when users hover over it."

### Alternatives (optional)

A text placed above or below the button can also suffice.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
Thanks for writing this, it isn't a bug though because it wasn't designed as a button.

We can look to work on improving the UX soon
