### ISSUE TITLE
Video or voice chat feature, Comment button

### ISSUE THREAD

**Issue by NftBabyy** [rotimi-best/classroomio#107]
### Feature Description

I suggest that this would allow the students to communicate and collaborate in real time. They can assignments, ask questions and also share more ideas effectively. It brings collaborative learning experience.

For comments, I feel having a comment button would provide a convenient way for the students or the participants to leave comments on a specific materials, assignments or videos. My idea is making the comment button a public one. I also didn't see if the teacher can host a live video to teach students while going through the demo.

### Proposed Solution

The video chat or voice chat should be incorporated to the platform.
And also the comment button.

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
Thank you for your recommendation.

1. Video chat right now isn't on the road map because there are great tools already solving that problem - Meet and Zoom. We plan on probably integrating the for now.
2. We already have a comments feature on the right side of each lesson.
https://jam.dev/c/18efc491-ba0f-44df-916e-8c590ff4e8d6
