### ISSUE TITLE
Inviting Students 

### ISSUE THREAD

**Issue by R3mee** [rotimi-best/classroomio#109]
Feature Description

The "Invite Student" feature allows teachers to easily send invitations to students who wish to join the classroom. Teachers can enter the student's email address and click "send invitation". The student will then receive an email with instructions on how to join the classroom. This feature will make it easier for teachers to manage their classrooms and for students to join them.

The "Invite Student" button will be located in a prominent place on the classroom page. It will be labeled clearly and will be easy to find. The button will open a new page with a field for the student's email address. The teacher will be able to type in the email address or paste it from the clipboard. The teacher will then be able to click "Send Invitation" to send the invitation. 

The invite student should contain:
- The name of the teacher who sent the invitation.
- The name of the classroom.
- The date and time of the classroom.
- A brief description of the classroom.
- The link to join the classroom.
- The option to decline the invitation.
This information will be clearly presented in the email, and it will be easy for the student to understand and take action. 

 The Value of this feature, is that first, it will help teachers to connect with their students more easily and efficiently. Second, it will help students to stay informed and organized by having all the information they need in one place. By making it easier for teachers and students to connect and communicate, this feature will improve the overall learning experience on the platform. 

### Use Case

A Scenario is a Teacher who is planning a new course on the classroom platform. She wants to invite her students to join the course so they can access the materials and interact with each other. Without the 'Invite Student' feature, the teacher would have to send each student an email with the information about the course, which would be time-consuming and inefficient. With the 'Invite Student' feature, the teacher can easily and quickly send an invitation to all her students at once. The students can then accept or decline.

Users would interact with the 'Invite Student' feature in a few simple steps. First, the teacher would select the students they want to invite from a list of students in the system. Next, the teacher would click the Invite Student button and choose how the invitation should be sent (email, SMS, etc.). Finally, the teacher would review the information and click 'Send' to send the invitation. The students would then receive the invitation and be able to accept or decline it. This feature is important because it gives the process of inviting students to the classroom, saving time and effort for both teachers and students.

### Proposed Solution

The proposed solution would be implemented through a combination of user interface UI and user experience UX design considerations. The UI design would focus on making the process of inviting students easy and intuitive, with a clean and simple interface that is easy to navigate. The UX design would focus on ensuring that the process is smooth and efficient, minimizing the number of steps required to invite students and providing clear guidance at each step. This combination of UI and UX design would create a user-friendly and effective solution for inviting students to a classroom.

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
Thanks for this issue, we already have a way to invite students in the dashboard.

Improvements to this feature can come later on. Thanks

![image](https://github.com/rotimi-best/classroomio/assets/31730715/d8f18394-978a-4452-b61c-0cee12e305bb)
