### ISSUE TITLE
Student not being able to view quiz issued by teacher

### ISSUE THREAD

**Issue by NftBabyy** [rotimi-best/classroomio#111]
I created a demo account for myself as a teacher and that of a student.

I issued a quiz assignment(one of the html quiz templates) to the student but the student didn’t see it on her dashboard

**Comment by rotimi-best** [comment]
@NftBabyy Please can you add the video that reproduces this bug

**Comment by cannarron** [comment]
So on my end, the exercise doesn't show at all from the student's dashboard, it only shows a progress bar but no content. Here is a [video showing this](https://drive.google.com/file/d/1JAH-NThg89T_Tc8dWuh5V---0wEafWsS/view?usp=drive_link)

**Comment by rotimi-best** [comment]
Thank you @cannarron, working on the issue now.

**Comment by rotimi-best** [comment]
This issue is now fixed
