### ISSUE TITLE
Integrate Drizzle ORM shared across all projects

### ISSUE THREAD

**Issue by elvis-ndubuisi** [rotimi-best/classroomio#113]
### Feature Description

Integrate Drizzle ORM shared across all projects

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
@elvis-ndubuisi The drizzle integration will only be for the mono repo, it shouldn't be for the whole project.

I think it should be together with this issue

https://github.com/rotimi-best/classroomio/issues/112
