### ISSUE TITLE
Hide email of people in a course

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#114]
### Feature Description

Replace emails of people in a course with 3 asterisks.

Requirement
- leave the first letter in the email
- leave the last letter in the email (before @)
- replace all other letters in between with 2 asterisks.

For example
```johndoe@gmail.com``` - ```j***e@gmail.com```
```ibukunoluwa@udemy.com``` - ```i***a@udemy.com```
```elon@x.com``` - ```e***n@x.com```

![image](https://github.com/rotimi-best/classroomio/assets/31730715/04e661c8-c7e4-4cab-ab26-346fa7b04417)

### Use Case

In case I want to share a screenshot  of the peoples tab but I don't want to share the emails.

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by bilalshaikh292** [comment]
heyy @rotimi-best  is the issue still open ? I would like to contribute ?

**Comment by Dun-sin** [comment]
Hi @rotimi-best I'm ready to take this

**Comment by rotimi-best** [comment]
@bilalshaikh292 Thank you for volunteering to work on this however I had already reached out to @Dun-sin to help out with this one.

Will you be interested in working on this issue: https://github.com/rotimi-best/classroomio/issues/116
