### ISSUE TITLE
Supabase doesn't notify the app when JWT is expired

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#115]
### Issue Description

This screenshort shows how the JWT is expired and yet a new token isn't requested and other requests fail.

<img width="1278" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/d7f42d77-0421-4cc8-a25d-5acdd2bec7e4">

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Dun-sin** [comment]
If jwt has expired, it should log the user out right? That's how I see it done usually at least

**Comment by rotimi-best** [comment]
@Dun-sin  Yeah there are 2 options here:

1. It gets the auth token automatically and keep the user logged in
2. It redirects the user to the login page to reauthenticate.

We want the first option.

Supabase has this function `supabase.auth.onAuthStateChange` that I expect to tell me when a user is logged out however this issue is that it isn't doing that. Actually sometimes option 1 happens but some times it doesn't and I don't know why.

<img width="1033" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/f7e35a5e-f2e3-45c1-920c-72069ab978e7">
