### ISSUE TITLE
Home page on the teacher's view

### ISSUE THREAD

**Issue by the-techgurl** [rotimi-best/classroomio#119]
![Courses - ClassroomIO - Google Chrome 12_19_2023 10_33_31 PM (2)](https://github.com/rotimi-best/classroomio/assets/115714559/3990e118-f784-41fc-bf8f-08c7931a748f)

### Improvement Description

There are two expandable icons next to the name of the organization when it should be just one, the dropdown icon.

### Rationale

Typically the two expandable icon gives off a reduction or addition action at first glance and that is not what it's intended to.

### Proposed Solution

Checkout the icon from [carbon-icon-svelte](https://carbon-icons-svelte.onrender.com/) and replace the current icon with this one.

<img width="1299" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/291001c9-ed78-44a0-91fe-ee20d698bdbd">

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [x] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by the-techgurl** [comment]
@rotimi-best

**Comment by rotimi-best** [comment]
@the-techgurl can you please add a screenshot with an arrow pointing to the particular place so it is easy to understand

**Comment by anishyadavv** [comment]
can I work on this issue? @rotimi-best

**Comment by rotimi-best** [comment]
@anishyadavv, sure. I can assign it to you.

Do you mind joining our discord so we can further discuss this task? https://dub.sh/ciodiscord

**Comment by anishyadavv** [comment]
sure
