### ISSUE TITLE
Creating a comprehensive style guide 

### ISSUE THREAD

**Issue by the-techgurl** [rotimi-best/classroomio#121]
### Improvement Description

For design contributions to be done with ease, we'll be creating a comprehensive style guide that will contain the important elements needed.

### Rationale

The style guide will consist of;

- color style (using tailwind to generate toners)

- Typography (both mobile and web)

- Buttons

- Component states (error, active, inactive)

- Grid (mobile and web)

- Shadow styles (elevated cards)

- Accessibility (stark, A11y-color contrast checker(these are plugins to check for accessibility))

### Proposed Solution

The elements listed above could be viewed as the bedrock of most design contributions and the list will be improved as time goes on.
The tasks have been shared amongst contributors and there is still opportunity for other contributors to be a part.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by boarss** [comment]
Thanks for this, I am currently working on the buttons and typography for the style guides.

**Comment by the-techgurl** [comment]
> Thanks for this, I am currently working on the buttons and typography for the style guides.

@rotimi-best could you please assign @boarss to this issue?

**Comment by rotimi-best** [comment]
Done
