### ISSUE TITLE
[DOCS]: improvement of dx for gitpod

### ISSUE THREAD

**Issue by Dun-sin** [rotimi-best/classroomio#122]
### Improvement Description

The autofill for env is great but for Gitpod the url isn't localhost

### Proposed Solution

Show a way to find the right URL for the .env
![image](https://github.com/rotimi-best/classroomio/assets/78784850/7d8cfb88-ce68-489d-9324-664e61f55ecd)

**Comment by Dun-sin** [comment]
> @Dun-sin Thanks for opening this issue. I have been quite busy due to the holidays so I haven't been able to respond to this.
> 
> Do you mind explaining more about this issue? I don't really understand the suggested improvement here.

Instead of localhost, tell the Devs how to find the proper url for gitpod.

Because gitpod output url isn't localhost

**Comment by rotimi-best** [comment]
Will you be interested in taking this one? Where do you think will be a good place to keep this info? README or a part of our documentation https://classroomio.com/docs

**Comment by rotimi-best** [comment]
I discussed with @Dun-sin and this is the action point for this task:

"Write somewhere in the gitpod docs that gitpod doesn't use localhost but uses its URL after starting the whole services. Then also mention that the right URLs to get the project running is automatically inserted into the .env file."

Note there is a documentation page for gitpod already that you might need to improve [here](https://www.classroomio.com/docs/contributor-guides/gitpod)
