### ISSUE TITLE
Everything in Teams?

### ISSUE THREAD

**Issue by Emmo00** [rotimi-best/classroomio#125]
### Issue Description

In the pricing section of the home page, under the `Teams` section. the first item there is `Everything in Teams`. Shouldn't that be `Everything in Pro`?

### Screenshots (optional)

![image](https://github.com/rotimi-best/classroomio/assets/88244468/273e8086-7277-4837-a57c-94fb6ed0bb37)

### Operating System [e.g., Windows 10]

Windows 10

### Browser [e.g., Chrome, Firefox]

Edge

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Emmo00** [comment]
.take

**Comment by Emmo00** [comment]
I could make a PR if this is the case..

**Comment by rotimi-best** [comment]
@Emmo00 Very nice catch. Thank you. Please go ahead with the PR
