### ISSUE TITLE
When a poll is published, send a notification to all students

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#128]
### Feature Description

Ideally this should be a supabase edge function that sends an email to all students, when I update the status of a poll in a course.

<img width="387" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/6ef3ddea-e18f-4afd-922d-97788895bcdb">

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Toyin5** [comment]
Can I get assigned to this?
And more expplanation please
