### ISSUE TITLE
Sidebar is open by default on mobile

### ISSUE THREAD

**Issue by Chifez** [rotimi-best/classroomio#135]
### Issue Description

The sidebar for the LMS dashboard and course page is open by default when i navigate to a new route on mobile

### Steps to Reproduce

on mobile,
- Go to your student LMS dashboard
- Click on learning 
- Select a course

### Expected Behavior

The sidebar should be closed by default unless when toggled by clicking the hamburger menu

### Current Behavior

The sidebar stays open by default for both the dashboard and the course page

### Screenshots (optional)

https://github.com/rotimi-best/classroomio/assets/69228399/c1d0b11e-248f-41c9-8e35-ad3da3636f82

### Operating System [e.g., Windows 10]

windows 10

### Browser [e.g., Chrome, Firefox]

chrome

### Environment (locally, production, selfhosted)

production

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by rotimi-best** [comment]
@Chifez Can you please fix this bug

**Comment by rotimi-best** [comment]
fixed here https://github.com/rotimi-best/classroomio/pull/138
