### ISSUE TITLE
Create classroomio blog

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#139]
### Feature Description

The blog will be very simple. We don't have a design for this, instead we will be following a similar structure to documenso.

Visit documenso.com/blog, 

1. That is the first page that you need to implement
<img width="1251" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/c006f728-041c-4679-b26a-c6d7947e0e62">

2. Click on any blog link and you will be redirected to a blog page. This is the second page you need to implement.
<img width="1224" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/721c099c-4e32-4bb9-bb0b-547f8469fcc8">

### Proposed Solution

Follow this tutorial to implement blogs using markdown in svelte

https://joyofcode.xyz/sveltekit-markdown-blog

Ideally start from here
<img width="891" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/97df84bf-27de-4a25-a981-f814543a6453">

and end here
<img width="1113" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/78f39b6b-87db-4f9b-a738-886fc54b866f">

Please pay attention in this post that instead of `post` we should have `blog` and the routes you create should be in `apps/classroomio-com`

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Chifez** [comment]
this is the current state of the blog

https://github.com/rotimi-best/classroomio/assets/69228399/acfc5b30-5843-402c-8412-951851fac626

**Comment by rotimi-best** [comment]
Love it. Will do some tweaks and I think it is good to go

**Comment by Chifez** [comment]
alright
