### ISSUE TITLE
Improve the Sign-up Section on ClassroomIO Documentation

### ISSUE THREAD

**Issue by Lanietodev** [rotimi-best/classroomio#153]
### Improvement Description

Provide better background information at the beginning to help users with context about the purpose and significance of the documented instructions. Also, use bold formatting for UI elements in the steps to make them stand out and easier to follow. See [Google style guide](https://developers.google.com/style/ui-elements#formatting) for more information.

### Rationale

It'll help users better grasp the purpose behind the instructions and navigate the steps more effortlessly.

### Proposed Solution

Clearly yet thoroughly describe background information and establish a consistent formatting style throughout the documentation.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
Thank you @Lanietodev for creating the issue. Please let me know when you are ready to work on it.

**Comment by Lanietodev** [comment]
Reopening the issue as I mistakenly closed it.
