### ISSUE TITLE
Hover on Navigation bar

### ISSUE THREAD

**Issue by pranay911** [rotimi-best/classroomio#156]
### Feature Description

We propose the addition of a hover effect to the navigation bar on the Classroomio website to enhance user experience and improve visual feedback. Currently, our website's navigation bar lacks interactive feedback, which can diminish user engagement and navigation clarity.

### Use Case

The primary objective of this feature is to provide visual cues to users when they hover over navigation items, thereby improving navigation intuitiveness and user interaction.

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
@pranay911  Thanks for opening this issue. Will you be interested in working on this issue?

**Comment by pranay911** [comment]
@rotimi-best Yes. Thanks

**Comment by rotimi-best** [comment]
Closing for now until @pranay911 is ready to work on it. We can open it back
