### ISSUE TITLE
Convert repo into a monorepo

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#16]
Using a tool like Turbo repo, it would be nice to move all of our repos into one.

The repos we have now are the following:

1. Dashboard: https://github.com/rotimi-best/classroomio
2. Docs: https://github.com/rotimi-best/docs.classroomio.com
3. ClassroomIO.com: https://github.com/rotimi-best/classroomio.com

Acceptance criteria

This repo should be converted into a mono repo
We should have the dashboard, landing-page, docs, and server all in this repo

**Comment by shyakadavis** [comment]
Hi, @rotimi-best 

Does it have to be `Turbo`? I did set up a monorepo once with `pnpm workspaces` and it was easy imo. Though, I don't know about expectations for your use case.

**Comment by rotimi-best** [comment]
This would also be great. Can you work on this?

**Comment by elvis-ndubuisi** [comment]
I can convert the project to a turbo or Lerna mono-repo. Just arrived here though. 

How do i contribute

**Comment by elvis-ndubuisi** [comment]
@rotimi-best I use turbo + yarn or pnpm the most. turbo reduces build time, has caching features, and has great docs for most frontend frameworks. Lerna on the other hand; I just started using but only with multiple node packages.  I don't know much about the features but both rely on creating a workspace with any node package manger and setting up the configurations.

**Comment by rotimi-best** [comment]
That's cool. Can you implement the turbo and pnpm?

**Comment by elvis-ndubuisi** [comment]
@rotimi-best yes

**Comment by rotimi-best** [comment]
Nice, please go for it @elvis-ndubuisi
