### ISSUE TITLE
Finish button should be disabled until the AI is done generating the exercises

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#160]
### Issue Description

In this image, when we try to create a new exercise with AI, the Finish button is enabled before the AI has generated any exercise which leads to a bug.

<img width="867" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/6bc7daed-8089-4eee-8e28-7b5667698bb3">

### Steps to Reproduce

Go to a Lesson
Add some lesson note
Go to Exercise tab
Click Add
Choose AI
Then you'd see the Finish button is enabled

If you click it, you'd get an exercise without a title and an empty question which is a bug

### Expected Behavior

At the last step make sure to disable the Finish button

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by R4Rohit23** [comment]
Hii @rotimi-best I would like to work on this issue/bug.

**Comment by rotimi-best** [comment]
Hey @R4Rohit23, go for it
