### ISSUE TITLE
Upon clicking Save, redirect to Exercises page

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#161]
### Feature Description

When editing an exercise and I hit on the Save button.
<img width="966" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/73ad3ad1-18f6-4bcb-b2aa-801a4ecbc964">

Redirect to the Exercises page
<img width="967" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/fe9ab41a-d548-4118-a798-fa6c871e582d">

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Toyin5** [comment]
Can I get assigned to this? @rotimi-best

**Comment by rotimi-best** [comment]
@toyin5 sure go for it.
