### ISSUE TITLE
Lesson date on dark mode has a white background and white text

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#18]
On dark mode make the date input on the lessons page to `bg-neutral-800` and `text-white`

<img width="1245" alt="Screenshot 2023-11-10 at 22 49 16" src="https://github.com/rotimi-best/classroomio/assets/31730715/b0860124-0008-4b65-8426-2e3f24e49722">

**Comment by R4Rohit23** [comment]
Hii @rotimi-best I would like to work on this issue.

**Comment by rotimi-best** [comment]
So sorry I am just seeing this now. I need to look into my notifications settings.

Thanks for the interest in this task 😎, I have a pending issue to document local setup of supabase in order for new contributors to contribute to the project.

Can you join our discord classroomio.com/discord for us to discuss more about this?

**Comment by rotimi-best** [comment]
@R4Rohit23 Please can you share how far you've come with this issue?

**Comment by R4Rohit23** [comment]
@rotimi-best Sorry for not seeing the messages. I was on the vacation. I will start working on tomorrow. If anybody wants to opt for this issue so they can go forward.

**Comment by rotimi-best** [comment]
There is no one for now, it's an easy fix and I'd want you to have your first win 🏆 😃
