### ISSUE TITLE
ERROR: column "provider_id" of relation "identities" does not exist 

### ISSUE THREAD

**Issue by mehdi-ra** [rotimi-best/classroomio#181]
### Issue Description

Getting this error on running command: `pnpm supabase start`
```
Applying migration 20231115082347_remote_schema.sql...
Applying migration 20231118210545_profile.sql...
Applying migration 20231207061507_update_get_courses.sql...
Applying migration 20231213104402_course_metadata.sql...
Applying migration 20231213105201_organizationmember_author_profile_id.sql...
Applying migration 20240212110855_add_courseid_to_community_question.sql...
Seeding data supabase/seed.sql...
ERROR: column "provider_id" of relation "identities" does not exist (SQLSTATE 42703)
```

### Steps to Reproduce

- Clone The Main branch.
- Follow the setup steps on the GitHub repository.
- Run `pnpm supabase start`

### Operating System [e.g., Windows 10]

Ubuntu 20.04

### Browser [e.g., Chrome, Firefox]

--

### Environment (locally, production, selfhosted)

selfhosted

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by mehdi-ra** [comment]
With `--debug`:
```
2024/02/25 12:37:34 PG Send: {"Type":"Describe","ObjectType":"S","Name":"lrupsc_1_2"}
2024/02/25 12:37:34 PG Send: {"Type":"Sync"}
2024/02/25 12:37:34 PG Recv: {"Type":"ParseComplete"}
2024/02/25 12:37:34 PG Recv: {"Type":"ParameterDescription","ParameterOIDs":[]}
2024/02/25 12:37:34 PG Recv: {"Type":"NoData"}
2024/02/25 12:37:34 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
2024/02/25 12:37:34 PG Send: {"Type":"Parse","Name":"lrupsc_1_3","Query":"--\n-- Data for Name: identities; Type: TABLE D
ATA; Schema: auth; Owner: supabase_auth_admin\n--\n\nINSERT INTO \"auth\".\"identities\" (\"provider_id\", \"user_id\", \
"identity_data\", \"provider\", \"last_sign_in_at\", \"created_at\", \"updated_at\") VALUES\n\t('01676a50-bb56-4c5e-8a61-
fb9e9190fb10', '01676a50-bb56-4c5e-8a61-fb9e9190fb10', '{\"sub\": \"01676a50-bb56-4c5e-8a61-fb9e9190fb10\", \"email\": \"
test@test.com\"}', 'email', '2023-11-22 10:09:32.225444+00', '2023-11-22 10:09:32.225521+00', '2023-11-22 10:09:32.225521
+00'),\n\t('7ac00503-8519-43c8-a5ea-b79aeca900b1', '7ac00503-8519-43c8-a5ea-b79aeca900b1', '{\"sub\": \"7ac00503-8519-43c
8-a5ea-b79aeca900b1\", \"email\": \"admin@test.com\"}', 'email', '2023-12-16 14:04:38.302264+00', '2023-12-16 14:04:38.30
2326+00', '2023-12-16 14:04:38.302326+00'),\n\t('0c256e75-aa40-4f62-8d30-0217ca1c60d9', '0c256e75-aa40-4f62-8d30-0217ca1c
60d9', '{\"sub\": \"0c256e75-aa40-4f62-8d30-0217ca1c60d9\", \"email\": \"student@test.com\"}', 'email', '2023-12-18 17:08
:57.410285+00', '2023-12-18 17:08:57.410344+00', '2023-12-18 17:08:57.410344+00')","ParameterOIDs":null}
2024/02/25 12:37:34 PG Send: {"Type":"Describe","ObjectType":"S","Name":"lrupsc_1_3"}
2024/02/25 12:37:34 PG Send: {"Type":"Sync"}
2024/02/25 12:37:34 PG Recv: {"Type":"ErrorResponse","Severity":"ERROR","SeverityUnlocalized":"ERROR","Code":"42703","Mes
sage":"column \"provider_id\" of relation \"identities\" does not exist","Detail":"","Hint":"","Position":130,"InternalPo
sition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName"
:"","File":"parse_target.c","Line":1061,"Routine":"checkInsertTargets","UnknownFields":null}
2024/02/25 12:37:34 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
2024/02/25 12:37:34 PG Send: {"Type":"Terminate"}
ERROR: column "provider_id" of relation "identities" does not exist (SQLSTATE 42703)
```

**Comment by rotimi-best** [comment]
Hi @mehdi-ra, thanks for reporting this issue.

We used to have this issue however we already fixed it in our seed file.

Can you please pull the latest of main and try it again?

**Comment by rotimi-best** [comment]
@mehdi-ra can you please verify on your end to make sure it is solved?

I want to make sure it didn't come up again

**Comment by rotimi-best** [comment]
will you be interested in contributing to any issue?

**Comment by rotimi-best** [comment]
@mehdi-ra I can verify that this issue still exists for some users.

Can you try this solution: https://github.com/supabase/supabase/issues/19620#issuecomment-1862304039.

Thanks

**Comment by mehdi-ra** [comment]
Yes I will and I'll try to open a PR if you agree dear @rotimi-best to fix this issue.

**Comment by rotimi-best** [comment]
The issue is fixed, you just need to clear a temporary data on your machine and try it again.

```
rm -rf supabase/.temp
```

Running the command on my machine works fine.
<img width="550" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/45e478bd-23f5-417a-be03-6a2a47e204db">

**Comment by mehdi-ra** [comment]
I can confirm that the issue is fixed.
Thank you very much @rotimi-best

**Comment by mehdi-ra** [comment]
No, The problem persists.
Depending on the link of the issue you posted earlier I just updated the version of the Supabase and It's start working.

It seems the problem is about the Postgres Version and the SQL.

I don't know but I'm worry if this fix can cause any runtime problems but as I said the specific problem is gone after increasing version of supabase to `1.128.1`.

**Comment by mehdi-ra** [comment]
Please if you have similar problem, Check the solution and if it is worked for you, consider sending one little comment down below.

Plus, if you add more detail about the environment it can be helpful because it seems this problem relies on environment.

Thank you very much.

**Comment by rotimi-best** [comment]
Thanks @mehdi-ra, that worked.
