### ISSUE TITLE
docs: Create an exercise

### ISSUE THREAD

**Issue by Lanietodev** [rotimi-best/classroomio#194]
### Feature Description

It'll cover a clear and concise step-by-step guide on how to create an exercise complete with visuals.

### Use Case

It'll help ClassroomIO admins easily navigate the interface to create exercises.

### Proposed Solution

It'll contain a very simple structure. It should follow documentation best practices to ensure it caters to user needs.

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
@Lanietodev This is amazing. Thank you. This contribution would be highly appreciated. 🫡👍🏽
