### ISSUE TITLE
No validation on newsfeed post and comment

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#214]
### Issue Description

Add a zod validation like we have when you make a community post to the news feed post and comment.

1. There should be a minimum of 5 characters before accepted
2. Show error below input if validation fails

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Toyin5** [comment]
@rotimi-best can I work on this?
