### ISSUE TITLE
Add Lesson Modal duplicates the lesson after clicking the "save" button.

### ISSUE THREAD

**Issue by tunny17** [rotimi-best/classroomio#228]
### Issue Description

When you click on "save" in the addLessonModal, it creates two instances of the new lesson.

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rotimi-best** [comment]
Not reproducable
