### ISSUE TITLE
Research and implement selfhosting

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#238]
### Feature Description

This is more of an investigation issue that aims to help us understand what the state of the art tool or approach other OS companies are using to empower users to self host.

#### Things to pay attention to
- We will support multiple ways to selfhost
- Ideally there should be a docker approach, one click solutions and any other option

#### OS projects to look at
- Dub.co - https://dub.co/docs/self-hosting
- Formbricks - They have a whole section for [selfhosting](https://formbricks.com/docs/self-hosting/deployment)
- Cal.com - https://cal.com/docs/introduction/quick-start/self-hosting
- Appwrite - https://appwrite.io/docs/advanced/self-hosting
- Novu - https://docs.novu.co/self-hosting-novu/introduction

#### Other things to do
- Create a coolify template for classroomio
- Ideally we should also selfhost supabase in the same docker network.

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
The simplest way to get this out the door is to support one click Vercel and Cloudflare deploys.

Todo

- [ ] Move from subdomains to subroutes for SELFHOSTING
- [ ] Write blog post to deploy to Vercel
- [ ] Write blog post to deploy to Cloudflare

**Comment by rotimi-best** [comment]
Closing for now until people are asking for the sub-routing feature

Will recommend for now people use the sub domain approach

```
app.yourdomain.com - dashboard
orgSiteName.yourdomain.com - the lms of an organization
```

**Comment by Livvux** [comment]
yeah we need a coolify template
