### ISSUE TITLE
[lw1] Multi translation support

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#25]
**Acceptance criteria**

1. Implement language support in repo
2. The whole UI should support at 5 languages

    1. English
    2. Chinese
    3. Hindi
    4. French
    5. Portuguese
  
3. Implement a language switcher

**Comment by t-bello7** [comment]
Hello, Can I work on this

**Comment by rotimi-best** [comment]
Hi @t-bello7, thanks for the interest. Some else would be working on this one.

Would you be interested in joining our discord server so we discuss what kind of issues interests you?

https://dub.sh/ciodiscord
