### ISSUE TITLE
Course Waitlist

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#26]
**Summary**: Send students a link, they answer some questions, they enter their email and we send them the result of the form they just filled.

**Source**: 1-on-1 with [Yucheng](https://twitter.com/lyc_zh)

**MVP Goal:**

1. Create a form with questions and selected answers
2. Add welcome page
3. Ask for email at the end to get result
4. Get result in email
5. Add email of applicant into waitlist

**Comment by rotimi-best** [comment]
Progress so far 

<img width="1296" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/c5fd0e13-b152-4d12-a0b0-bfdd4519fdae">

**Comment by rotimi-best** [comment]
- [ ] implement first question - edit mode
- [ ] implement last question - edit mode
- [ ] implement multiple answer question - edit mode
- [ ] implement preview mode of all 
- [ ] save created questions to db
- [ ] add share functionality
- [ ] implement play mode

**Comment by cannarron** [comment]
Can I work on the backend of this
