### ISSUE TITLE
Gitpod setup of ClassroomIO

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#29]
Following the setup guide in the README, come up with a Gitpod setup where people can click one button and get started contributing to the repo from their browser.

**Comment by rotimi-best** [comment]
Sure please go for it. Thanks

**Comment by rotimi-best** [comment]
Hey @obakeng-develops, have you started work on this?

**Comment by obakeng-develops** [comment]
hey @rotimi-best, not yet. I'll get started on it today.
