### ISSUE TITLE
Add course drop down to the new question page

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#31]
When a user wants to ask a new question, beside the title of the question on the right hand side, ask the user to select a course (from the courses they belong to) and it should be a required field.

Once a course is associated with a question, make sure the query to fetch the questions are filtered by a course that the current user belongs to.

<img width="1261" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/eaa66d35-a177-4176-adb2-f73121438803">

Requirements to work on this task:
- Frontend work
- Supabase related work.

Reach out to @rotimi-best if you are interested in picking this one

**Comment by Macarthur-yaw** [comment]
I want to pick this up

**Comment by rotimi-best** [comment]
@Macarthur-yaw Sure you can. Please let me know if you need anything

**Comment by rotimi-best** [comment]
As regards this one the expectation is that you have already setup the project locally and you are familiar with the Ask Community page.

@Macarthur-yaw, can you please confirm if that's the case?

**Comment by Macarthur-yaw** [comment]
Just started working on it

**Comment by rotimi-best** [comment]
@Macarthur-yaw Okay great, please go for it 😀

**Comment by carraya** [comment]
has this issue been resolved? if not, I could pick it up if @Macarthur-yaw doesn't have the bandwidth atm.

**Comment by CBID2** [comment]
I was going to volunteer for this @rotimi-best, but if you want to take this on, that’s fine.
