### ISSUE TITLE
QR code to join a course

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#349]
## Current invite modal
<img width="1384" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/de2e5658-8b7a-43fd-b9c9-abf693a116b6">

## The new update
<img width="657" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/8b33aa5d-bb30-4ae1-b5ea-6578f9db08d4">

The download button generates the image on the right.

I am open to suggestions on how to build this.

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by codiini** [comment]
I can pick this up
