### ISSUE TITLE
Bug when adding gift content for the course landing page

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#363]
### Issue Description

https://www.loom.com/share/49feba88ec9c4be98bcde0526ba56013?sid=8e9b82fe-5a03-40ce-b462-1e89aca26402

### Steps to Reproduce

- Open a course
- Go to landing page
- Click on the Pricing section
- Toggle to enable gift
- Enter a text
- Note: Don't remove the focus from the editor
- Click back button on editor

The whole content in the preview disappears.

### Expected Behavior

The content should behave the same when your focus is outside the editor.

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by codiini** [comment]
@rotimi-best I'll pick this up

**Comment by ib-best** [comment]
> @rotimi-best I'll pick this up

Sure go for it. Will assign it to you?
