### ISSUE TITLE
Redesign course content on course landing page

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#364]
## Before
<img width="714" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/2f237332-c880-4680-aa01-8a199c2daa42">

## After
<img width="508" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/b29d17ea-e136-4c4b-926b-971b180a59d9">

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Laurent-di** [comment]
I grab it :)
