### ISSUE TITLE
Fixed buttons cover text on lesson note

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#366]
### Issue Description

The buttons fixed at the bottom blocks content at the bottom of the lesson note.

![image](https://github.com/rotimi-best/classroomio/assets/31730715/719cd1fa-d200-40ad-99c5-d13592b05ca1)

### Expected Behavior

Add a padding buttom to the content so the buttons don't cover the content and the content has extra white space at the bottom.

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rotimi-best** [comment]
@Toyin5 Hey long time, how have you been 😃?

Sure I can assign it to you.

**Comment by pranavkangale5** [comment]
@rotimi-best where's the issue located exactly ? can you tell me the file that is needed to be changed .

**Comment by rotimi-best** [comment]
@pranavkangale5 I will recommend you setup the code locally and try using the feature so you understand how it works before trying to improve the UI.

When you have everything setup and are ready to get started, here is the location of component https://github.com/rotimi-best/classroomio/blob/main/apps/dashboard/src/routes/courses/%5Bid%5D/lessons/%5B...lessonParams%5D/+page.svelte#L398

**Comment by pranavkangale5** [comment]
@rotimi-best  i set up the complete code using gitpod . After trying dummy admin credentials as provided it is asking to verify now how do i verify admin@test.com

**Comment by smritidoneria** [comment]
Hey @pranavkangale5 , this functionality has not been added yet locally . 
here are the steps to solve the issue u are facing-
Open your supabase dashboard by visiting: http://127.0.0.1:54323/project/default/editor/17644
It should take you to the profile table.
<img width="937" alt="Screenshot 2024-07-14 at 8 42 54 AM" src="https://github.com/user-attachments/assets/8466f5aa-d199-4256-ba19-db4fd1c857ff">
find the row with the email admin@test.com, then change the value of is_email_verified to true
<img width="1102" alt="Screenshot 2024-07-14 at 8 43 38 AM" src="https://github.com/user-attachments/assets/8fcbb5fe-d747-41bb-b38e-156bb30ba6f4">

**Comment by smritidoneria** [comment]
hey @rotimi-best ,I would like to work upon this issue

**Comment by rotimi-best** [comment]
> Hey @pranavkangale5 , this functionality has not been added yet locally . here are the steps to solve the issue u are facing- Open your supabase dashboard by visiting: http://127.0.0.1:54323/project/default/editor/17644 It should take you to the profile table. <img alt="Screenshot 2024-07-14 at 8 42 54 AM" width="937" src="https://private-user-images.githubusercontent.com/109029101/348513341-8466f5aa-d199-4256-ba19-db4fd1c857ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDgxNzEsIm5iZiI6MTcyMTEwNzg3MSwicGF0aCI6Ii8xMDkwMjkxMDEvMzQ4NTEzMzQxLTg0NjZmNWFhLWQxOTktNDI1Ni1iYTE5LWRiNGZkMWM4NTdmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNTMxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTJmM2RjMzZiMDdmZmYyYWRlYTk3NjE5NjQyMmQzYjMwZjBhZGJiZDY5ZTJkMGIyMjMwYWRkM2MyZDU2NjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KnsAQGE16UjQvFeDjgeLoOxQmfgbBAmZIV5EYcYu62g"> find the row with the email [admin@test.com](mailto:admin@test.com), then change the value of is_email_verified to true <img alt="Screenshot 2024-07-14 at 8 43 38 AM" width="1102" src="https://private-user-images.githubusercontent.com/109029101/348513370-8fcbb5fe-d747-41bb-b38e-156bb30ba6f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDgxNzEsIm5iZiI6MTcyMTEwNzg3MSwicGF0aCI6Ii8xMDkwMjkxMDEvMzQ4NTEzMzcwLThmY2JiNWZlLWQ3NDctNDFiYi1iMzhlLTE1NmJiMzBiYTZmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNTMxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTNiYzU1MmZlYWJlZDQ4NTYyMzg3NzQ5MWM0NDUyZjUyNmM2ODQ4YTNjOTIzNTQ0ZWQzMWI2YmM4MzVkNzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChiKugIo3yAu8x9kCgRWYo3bqB-i0V4pUzW-mkiyTN0">

Thank you @smritidoneria for the help.

> hey @rotimi-best ,I would like to work upon this issue

Sure I can assign it to you. Thank you
