### ISSUE TITLE
docs: Student Dashboard

### ISSUE THREAD

**Issue by ade555** [rotimi-best/classroomio#369]
### Improvement Description

A complete documentation of the student dashboard. This will contain the necessary information about the features and limitations of the student dashboard.

### Rationale

It will assist students to understand the user interface of the dashboard and navigate it easily.

### Proposed Solution

It'll contain a very simple structure, following documentation best practices and cover all the necessary parts of the student dashboard feature.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by ade555** [comment]
Hi, @rotimi-best I'll like to work on this issue.

**Comment by rotimi-best** [comment]
> Hi, @rotimi-best I'll like to work on this issue.

Sure thanks. Assigning to you

**Comment by rotimi-best** [comment]
@ade555 Hey what's the progress on this?

**Comment by ade555** [comment]
Hi, @rotimi-best. Sorry about the delay. I should have this done before this week runs out.
