### ISSUE TITLE
[design] Enable different batches within a course

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#370]
### Feature Description

- An educator can create different batches within a course
- Each batch can have multiple students
- You can only make one batch active and the rest will be unactive
- When you open the course you should see it at the top of the course the active batch.

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by ShalomOhuegbe** [comment]
Please im interested in this issue
