### ISSUE TITLE
Submit lesson on click enter

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#373]
### Feature Description

In a self paced course, if the user hits enter on the new lesson modal trigger the submit functionality similar on the Save button

<img width="1064" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/b4a4be31-bb1c-4eb3-8c2c-bf86b36279d9">

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by iutkarsh077** [comment]
.take

**Comment by rotimi-best** [comment]
@iutkarsh077 Sure you can pick this.

**Comment by smritidoneria** [comment]
Hey @iutkarsh077 , are you working on this issue? if you are not, I would like to take this.

**Comment by rotimi-best** [comment]
Hey since @iutkarsh077 hasn't shown any progress on this. Can you pick this up @smritidoneria ?

**Comment by smritidoneria** [comment]
yes @rotimi-best ,I want to pick this up

**Comment by smritidoneria** [comment]
hey @rotimi-best , can you take a look into the pr #383 to close this issue
