### ISSUE TITLE
Error in Points Validation: Non-numeric Input Allowed in Exercise Modal

### ISSUE THREAD

**Issue by smritidoneria** [rotimi-best/classroomio#380]
### Issue Description

Inappropiate points validate. User do not get any error if they type anything except for number.

https://github.com/rotimi-best/classroomio/assets/109029101/2dc3bad8-76f8-4d9a-ad2e-1dc84b20178c

### Steps to Reproduce

1.Create a lesson
2.Make a exercise
3. Set the points for any question

### Expected Behavior

If the point type is not a number, it should an error message to the user saying to correct the points type.

### Current Behavior

It not showing any error  message if the user types any datatype other than number in the textfields of points

### Operating System [e.g., Windows 10]

MacOS

### Browser [e.g., Chrome, Firefox]

Safari

### Environment (locally, production, selfhosted)

Production

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by smritidoneria** [comment]
./take

**Comment by smritidoneria** [comment]
hey @rotimi-best , I want to work on this issue. I have debug this locally.

**Comment by rotimi-best** [comment]
@smritidoneria Oh wow, thank you for catching this bug.

Sure go for it.

**Comment by smritidoneria** [comment]
hey @rotimi-best , kindly review the pr #381 for this issue

**Comment by rotimi-best** [comment]
@smritidoneria I am trying to reproduce this bug but I couldn't. I can only enter numbers but no letters, what browser are you using?

**Comment by smritidoneria** [comment]
Safari, okay I also noticed that this works fine on chrome, maybe there is some browser compatibility issue with the textfield of shellte

**Comment by rotimi-best** [comment]
@smritidoneria 
I left you a comment on the PR, can you please see how to make the default `type="number"` enforce only numbers in Safari?
