### ISSUE TITLE
Visibility of chevron down icon

### ISSUE THREAD

**Issue by smritidoneria** [rotimi-best/classroomio#384]
### Issue Description

In every dropdown , chevron down icons is visible two times.
<img width="466" alt="Screenshot 2024-07-08 at 9 47 23 AM" src="https://github.com/rotimi-best/classroomio/assets/109029101/a102578c-fae5-4dd8-907f-391b529f3746">

### Steps to Reproduce

go to any lesson. 
make new exercise and then select the question type.

### Expected Behavior

icons should be visible only once.

### Operating System [e.g., Windows 10]

MacOs

### Browser [e.g., Chrome, Firefox]

Chrome

### Environment (locally, production, selfhosted)

production

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Laurent-di** [comment]
I can take

**Comment by rotimi-best** [comment]
Fixed by https://github.com/rotimi-best/classroomio/pull/403
