### ISSUE TITLE
 no functionality of close  icon  in create a course modal

### ISSUE THREAD

**Issue by smritidoneria** [rotimi-best/classroomio#386]
### Issue Description

The modal doesn't closes while clicking on the close icon of the create a couse modal.

https://github.com/rotimi-best/classroomio/assets/109029101/34d502e5-1b13-4221-8f92-bd71520f68d2

### Steps to Reproduce

open modal to create a new course
click on the close icon.

### Expected Behavior

the modal should close upon clicking on the close icon of the modal.

### Current Behavior

the modal is not closing.

### Operating System [e.g., Windows 10]

MacOs

### Browser [e.g., Chrome, Firefox]

Chrome

### Environment (locally, production, selfhosted)

production

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by smritidoneria** [comment]
hey @rotimi-best , I want to work upon this issue

**Comment by rotimi-best** [comment]
@smritidoneria Thank you for reporting this. I have fixed it
