### ISSUE TITLE
Incorrect Email Validation

### ISSUE THREAD

**Issue by smritidoneria** [rotimi-best/classroomio#389]
### Issue Description

The email in settings are not validating properly.

https://github.com/user-attachments/assets/7cc3ecb2-df9d-4e2f-a39b-5e28441aaa4e

### Steps to Reproduce

Go to settings
Update the Email

### Expected Behavior

Email should be validated first.

### Current Behavior

Emails are not validating.

### Operating System [e.g., Windows 10]

MacOs

### Browser [e.g., Chrome, Firefox]

Chrome

### Environment (locally, production, selfhosted)

Production

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by smritidoneria** [comment]
I have tried to find the solution of it using type="email" Iin Textfield .but it remains the same.
<img width="529" alt="Screenshot 2024-07-12 at 8 05 31 AM" src="https://github.com/user-attachments/assets/dc4b6c84-40cc-4aa1-9db5-947e6e1e9797">

**Comment by codiini** [comment]
@smritidoneria, thanks for catching the bug. I've made a PR to fix this. In general, for proper data validation, ClassroomIO uses Zod.
