### ISSUE TITLE
Unable to locate the "Sign Up" button

### ISSUE THREAD

**Issue by Gloriean** [rotimi-best/classroomio#39]
<img width="1671" alt="Screenshot 2023-11-22 at 23 09 59" src="https://github.com/rotimi-best/classroomio/assets/99972504/6d162050-e4fc-42f1-a9eb-41fa21a8b1f4">

@rotimi-best

**Comment by rotimi-best** [comment]
Hey @Gloriean, this is intentional because I want to discuss with people who want to try out the platform. You watch the demo of the whole application to understand the feature set.
 https://www.youtube.com/watch?v=ztiZ6vo2gg0&ab_channel=ClassroomIO
