### ISSUE TITLE
Signup with Google not working

### ISSUE THREAD

**Issue by eiidoubleyuwes** [rotimi-best/classroomio#390]
### Issue Description

The issue is that whan logging in with google the verification email is never sent.Its been 3 days since I signed up and no email has been sent to me. 

### Steps to Reproduce

1. Signup via google
2. click on resend verification email
3. Wait an eternity

### Expected Behavior

I expect an email to be sent

### Current Behavior

No email is sent

### Screenshots (optional)

![Screenshot from 2024-07-12 13-28-36](https://github.com/user-attachments/assets/d1b1ae07-4b4d-478d-a779-7e1c218c6259)

### Operating System [e.g., Windows 10]

Zorin OS

### Browser [e.g., Chrome, Firefox]

Chrome

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by smritidoneria** [comment]
hey @eiidoubleyuwes , have u tried resending it again?

**Comment by rotimi-best** [comment]
Hey @eiidoubleyuwes. Sorry about this.

Have you tried checking your spam folder?

**Comment by rotimi-best** [comment]
@eiidoubleyuwes I can see that you've already verified your email and you should be good now.

<img width="700" alt="image" src="https://github.com/user-attachments/assets/bd3106e7-8a7d-4d55-97f5-8dc89d1593ac">

**Comment by eiidoubleyuwes** [comment]
Thanks
