### ISSUE TITLE
Incorrect Validation of Username and FullName

### ISSUE THREAD

**Issue by smritidoneria** [rotimi-best/classroomio#397]
### Issue Description

If  either the username or the fullname is empty, the data has been saved successfully.

https://github.com/user-attachments/assets/f56abcc6-c911-4ebc-af97-73097366dc98

### Steps to Reproduce

go to settings, 
make username or full name empty,
save the changes

### Expected Behavior

The interface should show the error if the username or the full name is empty,

### Current Behavior

The user data has saved successfully

### Operating System [e.g., Windows 10]

MacOs

### Browser [e.g., Chrome, Firefox]

Safari

### Environment (locally, production, selfhosted)

Production

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by Toyin5** [comment]
Can I get assigned to this??
@rotimi-best

**Comment by smritidoneria** [comment]
I have open the pr to close this issue. kindly review the pr @rotimi-best
