### ISSUE TITLE
Some modification are not properly saved resulting in content loss

### ISSUE THREAD

**Issue by Marcpezin** [rotimi-best/classroomio#404]
### Issue Description

It already happened twice for me. I'm working on a course content, updating and saving from time to time - I'm noticing error messages about "translation failed" as well.

Reviewing my content after saving makes it visible, but switching pages or returning back later and my work disappeared entirely, not showing either into version history. I lost hours of work on this bug already which is really frustrating. 

### Steps to Reproduce

1. Create content
2. Save
3. switch or refresh page
4. Content is not there anymore

### Expected Behavior

Content I save should be saved... 

### Operating System [e.g., Windows 10]

Windows 10

### Browser [e.g., Chrome, Firefox]

Google Chrome

### Environment (locally, production, selfhosted)

Production

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rotimi-best** [comment]
@Marcpezin Oh I am so sorry about this. We have a versioning functionality where you can roll back to the certain state of your work.

Did you try it out.

**Comment by rotimi-best** [comment]
@Marcpezin I was able to reproduce the issue, so sorry you faced this. I have pushed the fix.

The cause of the issue was our RLS feature we just released few days ago and it was not allowing our versioning feature to work properly.

Apologies again.
