### ISSUE TITLE
[bug] after logout, organisation name in login page still remains

### ISSUE THREAD

**Issue by Gloriean** [rotimi-best/classroomio#42]
**Description:**
After the user logs out, the organization's name persists on the login and signup pages.
(I noticed that after I'd logged out of my previous account, my organization name still appeared on the login and signup page until I refreshed my page.)

**Steps to reproduce:**
1. Navigate to the settings section in your dashboard.
2. Select the "log out" button.

**Acceptance Criteria:** 
Upon a successful log-out, the organization's name and details should no longer be visible.

<img width="462" alt="Screenshot 2023-11-23 at 23 36 38" src="https://github.com/rotimi-best/classroomio/assets/99972504/3ff44a25-a49e-46a7-8cbd-3c18b5c04ad3">

<img width="479" alt="Screenshot 2023-11-23 at 23 34 37" src="https://github.com/rotimi-best/classroomio/assets/99972504/0a5579bf-4adb-491f-8efc-56f910e1ba8f">

**Comment by rotimi-best** [comment]
@Gloriean Can you please add the following to the description:

1. General description of the bug
2. Steps to reproduce
3. Acceptance criteria

**Comment by Gloriean** [comment]
Description:
After the user logs out, the organization's name persists on the login and signup pages.

Steps to replicate:
1. Navigate to the settings section in your dashboard.
2. Select the "log out" button.

Acceptance Criteria: Upon a successful log-out, the organization's name and details should no longer be visible.

**Comment by rotimi-best** [comment]
Thanks for this, I have added it to the original issue description.

Can you also show in the screenshot maybe with an arrow showing where the issue is? 

and also add a screenshot show how it is supposed to be once it is fixed, so whoever is picking it up can know if it is fixed.

You mentioned something to me in discord that I think is important and you should add it here: 

> I noticed that after I'd logged out from my previous account, my organization name still appeared on the login and signup page **till I refreshed my page.**

*till I refreshed my page.* is the key part, can you also explain that in the issue description at the top 😊 

Thank you 🙏

**Comment by cannarron** [comment]
Hi, can you assign me this cc @rotimi-best @Gloriean

**Comment by rotimi-best** [comment]
@cannarron, thanks for wanting to pick this up.

Did you reproduce it locally or on production?

Yeah I think you make a good point. However I think it would be more complicated to implement that.

I would say once the user hits the log out button you reset to organization data. This is the easiest way to implement this.

Please go for it 🚀. Let me know if you face any issues 👍🏾 😊

**Comment by cannarron** [comment]
Oh okay, noted

Yes I reproduced it locally

Alright thanks 😊
