### ISSUE TITLE
Setup testing environment

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#43]
### Improvement Description

We need a separate environment for testing

### Rationale

To avoid mixing testing data to production data

### Proposed Solution

We would need a way to trigger deploys to a testing environment on vercel.
Setup a different supabase project that replicates prod db

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by elvis-ndubuisi** [comment]
I would like to take on this task but....... I don't really understand what you mean by setting up a different test environment and avoid missing test data with production. Do you mean setting up a different supabase project for testing

**Comment by rotimi-best** [comment]
Thanks for the question. I meant setting up a different supabase project for testing.

This is helpful for the following reasons:

1. [Gloriean](https://github.com/Gloriean) does testing and a different environment where she can create test data would be great.
2. We can connect that to a CI/CD testing env that runs tests before we merge code into main.

**Comment by rotimi-best** [comment]
Not a priority right now.
