### ISSUE TITLE
Selfhost ClassroomIO

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#44]
### Feature Description

A user should be able to run the whole classroomio stack via docker.

### Use Case

Anyone interested in selfhosting can do that in a few steps

### Proposed Solution

- Docker compose file to spin up the service
- Important to add how to selfhost supabase https://supabase.com/docs/guides/self-hosting/docker
- Some documentation on how to do it.

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by SabAlej** [comment]
Hello @rotimi-best. Hope you are doing really great! Can I work on this issue? 🌻 I was wondering if this [config](https://github.com/SabAlej/classroomio/commit/cf4d20638d4d4eb00661147a9cbdcbcbe2ca1314) was close to your idea. And then add the documentation to set it up. Or am I totally lost? 🥲😅

**Comment by rotimi-best** [comment]
Wow @SabAlej, that's incredible. You wrote all that config?

Yes that's correct, you are on the right track

**Comment by SabAlej** [comment]
Hi @rotimi-best i got the docker-compose.yml from [here](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml) 🫣😅
