### ISSUE TITLE
Creating a new organisation under a specific organization keeps crashing

### ISSUE THREAD

**Issue by Gloriean** [rotimi-best/classroomio#45]
### Issue Description

On my dashboard, I tried creating a new organization, but it keeps crashing and returning an error 404 page. 

### Steps to Reproduce

1. Access your dashboard by clicking and entering your credentials into the email and password fields.
2. Click the button with the name of the organization.
3. Choose the "add" button to include a new organization.
4. Enter the name of the organization into the "organization" field.

### Expected Behavior

Upon selecting the "add organization" button, users should be able to successfully add a new organization without experiencing any crashes.

### Current Behavior

Creating a new organization keeps crashing. 

### Screenshots (optional)
https://jam.dev/c/b9a98536-35b9-410e-ae7f-a58baf7ca0e5

[2d7fbad4-3487-4d98-abd4-41b899efe604.webm](https://github.com/rotimi-best/classroomio/assets/99972504/c4c00351-5c4a-4ca1-b98a-f74b0c4e0d47)

### Operating System [e.g., Windows 10]

Macbook

### Browser [e.g., Chrome, Firefox]

Chrome

### Environment (locally, production, selfhosted)

Production

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rotimi-best** [comment]
Can you please use jam.dev to record the reproduction of this bug.

So we can see right away the issue and the error in the console.

**Comment by rotimi-best** [comment]
@Gloriean Please let me know when you see my previous comment, thanks

**Comment by Gloriean** [comment]
I've seen your comments.

**Comment by cannarron** [comment]
I've reproduced this issue

**Comment by rotimi-best** [comment]
@glorien, this fix has been merged thanks to @cannarron.

Please can you verify the fix on your end as well and close this issue if fixed

**Comment by Gloriean** [comment]
It's been fixed...

**Comment by rotimi-best** [comment]
Thanks a lot for verifying
