### ISSUE TITLE
Replacing cover image button on the landing page is not responsive

### ISSUE THREAD

**Issue by Gloriean** [rotimi-best/classroomio#46]
### Issue Description

When the user clicks the "Replace" button on the landing page to replace the default cover image for a specific course, the button is not active. 

### Steps to Reproduce

1. Log in to your dashboard by clicking and entering your credentials in the email and password fields.
2. Navigate to the "Courses" feature on your dashboard.
3. Choose a specific course from your created list.
4. Access the "Landing Page" option.
5. On the Page Builder page, click the "Header Section" option.
6. Opt for the "Replace Cover Image" button.

### Expected Behavior

The user should be able to successfully replace the default cover image without encountering any glitches.

### Current Behavior

The user can't replace the default cover image. 

### Screenshots (optional)
[replace.webm](https://github.com/rotimi-best/classroomio/assets/99972504/ca9eb4ce-0545-437f-8ead-4a961ab83e8a)

### Operating System [e.g., Windows 10]

Macbook

### Browser [e.g., Chrome, Firefox]

Chrome, Safari

### Environment (locally, production, selfhosted)

Production

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rotimi-best** [comment]
Thanks for reporting this bug. Can you please update the image and also add a jam.dev link.

Thanks 😊

**Comment by Sanket-Arekar** [comment]
I would like to work on this issue. Can you Please assign me this issue?

**Comment by rotimi-best** [comment]
Sure you can. Heads up on this one, this button referenced on this issue should work just like the Replace button on the Settings page within a course.

Please make sure to duplicate similar functionality. Thanks
