### ISSUE TITLE
Limit file size to upload in Course banner image

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#50]
### Issue Description

Right now users can upload any size of images as their banner cover image

### Steps to Reproduce

Watch this jam video: https://jam.dev/c/2044bdfc-638f-4e1c-b0dd-0f5f4a903946

<img width="1238" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/88c9c774-703a-4cc1-9e8c-cfa7f4442db2">

### Expected Behavior

1. Click upload image
2. If more than 500kb don't upload to supabase and show error
3. Text button should change to try again
4. If user clicks try again and same issue, go back to step 2
5. else upload the image to supabase and the existing flow should remain the same

Also make sure to update the text saying file limit is 500KB

### Current Behavior

Any file size can be uploaded

### Operating System [e.g., Windows 10]

All

### Browser [e.g., Chrome, Firefox]

All

### Environment (locally, production, selfhosted)

All

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Toyin5** [comment]
.take

**Comment by Toyin5** [comment]
Can I take up this issue?

**Comment by rotimi-best** [comment]
Sure, go for it. Can you join our discord https://dub.sh/ciodiscord and send me a DM so we can discuss this task
