### ISSUE TITLE
Add a "restart" icon, that when clicked regenerates the slug of a course

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#56]
### Feature Description

From the image below, you need to add a restart icon, (we use [carbon icons](https://carbon-icons-svelte.onrender.com/)) just beside the "Course Link" text.

When clicked it should regenerate the slug of a course.

The slug of a course is everything after this `https://ciodevs.classroomio.com/course/{SLUG_HERE}`.

![image](https://github.com/rotimi-best/classroomio/assets/31730715/e86badf1-1846-4c2a-9678-641da5f68a82)

## IMPORTANT

1. Pay attention to how we implement icons in the project, we first import a component call `IconButton`, pass some props to it and then wrap the icon around it. See this code for example https://github.com/rotimi-best/classroomio/blob/0e9214f717279d88cc99ae36637256282f11b682/apps/dashboard/src/lib/components/Apps/components/Poll/components/CreatePollForm.svelte#L90-L92

2. The icon to use is this one from Carbon Icons - `Refresh` and the prop size should be `16`

<img width="1280" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/a2fd3303-3322-4aca-9934-db4728d997d2">
**Note**: Make sure you look at other places how we import carbon icons: like here

https://github.com/rotimi-best/classroomio/blob/0e9214f717279d88cc99ae36637256282f11b682/apps/dashboard/src/lib/components/Apps/components/Poll/components/CreatePollForm.svelte#L9

3. The generate slug functionality already exists, see an example of how it is used on the course landing page. There is an imported function called `generateSlug`

https://github.com/rotimi-best/classroomio/blob/0e9214f717279d88cc99ae36637256282f11b682/apps/dashboard/src/lib/components/CourseLandingPage/components/Editor/index.svelte#L21

And then it is used here:

https://github.com/rotimi-best/classroomio/blob/0e9214f717279d88cc99ae36637256282f11b682/apps/dashboard/src/lib/components/CourseLandingPage/components/Editor/index.svelte#L116

### Use Case

If you rename the title of the course and you want a new slug

### Proposed Solution

Already explained above

### Additional Context

Already explained above

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
## Heads up
To generate a slug in the first place, you will need to open the Landing page of the course and hit save. This will generate the initial slug. 

## To test your work
Go back to the settings, update the title and then click the Refresh icon you just added. The course link should be updated and when you hit save and refresh the page, then the slug should still reflect.

**Comment by R4Rohit23** [comment]
Hey @rotimi-best I would like to work on this issue.
