### ISSUE TITLE
Implement unit test into the dashboard app

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#66]
Can we setup unit tests for the following:

1. [x] Utility functions: `apps/dashboard/lib/utils`
2. [ ] UI components: `apps/dashboard/lib/components`
3. [ ] Pages/Routes: `apps/dashboard/lib/routes`

**Comment by Toyin5** [comment]
Can I get assigned to this?
I will need help though

**Comment by rotimi-best** [comment]
@Toyin5 Sure, you can go for it.

Please note that the test should be only implemented for the `apps/dashboard` project.

Please let me know what help you'll need.

I think a good place to start with be from this [article](https://blog.logrocket.com/intro-testing-sveltekit-applications/)

<img width="964" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/510f7efc-ef04-4b7b-8f87-ff1f032d98f3">

**Comment by rotimi-best** [comment]
@Toyin5 We can implement Cyprus testing later for end to end testing

**Comment by rotimi-best** [comment]
There is still an issue with the pnpm-lock.yml file. Fixed it in this [branch](https://github.com/rotimi-best/classroomio/tree/feature/unittesting)

<img width="1038" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/1755d25e-dd6f-4e1b-a859-321793da70eb">

**Comment by Toyin5** [comment]
> There is still an issue with the pnpm-lock.yml file. Fixed it in this [branch](https://github.com/rotimi-best/classroomio/tree/feature/unittesting). Once you merge this into your branch, I will be clear to merge it.
> 
> <img alt="image" width="1038" src="https://private-user-images.githubusercontent.com/31730715/291873026-1755d25e-dd6f-4e1b-a859-321793da70eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzEzNjEsIm5iZiI6MTcwMzA3MTA2MSwicGF0aCI6Ii8zMTczMDcxNS8yOTE4NzMwMjYtMTc1NWQyNWUtZGQ2Zi00ZTFiLWE4NTktMzIxNzkzZGE3MGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDExMTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNTQ5MzliZTZhYmJmNjZhYzk0MTM0ZGQ5MjAyNDIwNzA4ZWQxMDJlZTkyNmRiOTY4YmZmNjkyYWQ4YmQ0ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bmwffqihRQj0PmJRUXFr94y9F9CyN0LsUD1jYWNZAu0">

I've merged the patch to the PR

**Comment by rotimi-best** [comment]
@Toyin5 Thank you for the unit test you put in place for the utils folder.

I have ticked it as complete.

We can move ahead to working on components testing

**Comment by rotimi-best** [comment]
Closing this PR as we have the first set of tests. If we need more I will reopen
