### ISSUE TITLE
Docker-less setup

### ISSUE THREAD

**Issue by olivierlambert** [rotimi-best/classroomio#67]
### Improvement Description

Sometimes, you might want to use the software in a regular VM (or small host, like a Raspberry Pi) without relying on Docker, especially outside a purely dev oriented environment.

### Rationale

From my personal point of view, I'm not using Docker nor want to manage containers in production. Doing a git pull and npm build is often enough to start in production mode and serve all of it via a reverse proxy (eg Nginx+LE). This also help to contain the dependency creep by knowing exactly the services you need and self-host them the way you want.

### Proposed Solution

Nothing specific is required outside to document how to achieve it in the official doc or README file. I'm open to participate in that direction if it's OK for the project :)

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
Thank you very much @olivierlambert. I am super happy to help you on your self hosting journey.

TBH I haven't selfhosted supabase before but I think the process should be well documented and smooth.

Do you mind sharing your use-case for classroomio 😃?

We can start taking baby steps to help you selfhost the whole stack, this is also gonna be helpful because we can document the selfhosting process in our [documentation](https://docs.classroomio.com/quickstart/selfhosting)

**Comment by olivierlambert** [comment]
Sure, the use case is pretty simple: we'd like to offer a training/certification program on our open source virtualization stack (see https://vates.tech for the details). We started to have some courses on slides, but having a solution to deliver the courses with a quiz and such will offer a nice experience.

Obviously, this means we'll probably know to interconnect many software together (or to have an SSO for our existing customer portal to make them connect to all our apps seamlessly) but this is not the priority right now.

So I'm exploring all the different Open Source LMS platforms, I don't need something super complicated, I'm not a university or something, it's few courses (probably 10 at max on the long run).

**Comment by rotimi-best** [comment]
Oh this makes sense. This was my exact problem with the existing open source solutions. The stack was either complicated to setup and uses some stale technologies or the feature sets were more best suited for enterprises.

Do you want to try out the platform first before investing the time in selfhosting?

I can give you a quick demo or give you access to the platform to try out the cloud version yourself - whichever you prefer 😃

**Comment by rotimi-best** [comment]
Sounds good. That's fine. Whichever is fine. Please feel free to continue the convo there or just shoot me an email best@classroomio.com

**Comment by olivierlambert** [comment]
Thanks, we'll focus on the tech part in here, and have a convo in parallel with the relevant people at Vates. Thank you again for your great software and also your time to answer!

**Comment by olivierlambert** [comment]
So I'm back and now starting to actively try to install the stack locally, without Docker :)

If I understand correctly, the app I want to use is the "dashboard" one. I need to build that app and then to connect it to Supabase (it's another topic for now).

However, if I go in the dashboard folder and try to do `npm i`, I'm already stuck with:
```
$ npm i
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/.npm/_logs/2024-01-18T12_06_42_206Z-debug-0.log
```

I'm using Node 18.

**Comment by rotimi-best** [comment]
Welcome back 😀. Not sure if I need to improve the communication in the README however to install the packages we use pnpm. 

That means you should run `pnpm i`

**Comment by olivierlambert** [comment]
So in short, I'm loading Nginx in front of `npm run preview` on a domain name, and when I'm loading it, I'm redirected to https://app.classroomio.com/404?type=org

**Comment by olivierlambert** [comment]
Okay so it's a bit better with `npm run dev` vs `preview`: now I have the main page. Do I have pre existing/default credentials?

If not, trying to register fails with:

![image](https://github.com/rotimi-best/classroomio/assets/1241401/c18c12f7-85e1-452a-ad8a-6c2716b8eff8)

**Comment by rotimi-best** [comment]
Oh, glad it worked. Yeah `npm run dev` is the command to get the frontend running.

@cannarron is actually working on a contributibution that adds dummy data into the db after running migrations. This gives you test users and courses to start interacting with.

You can't register (NetworkError when attempting to fetch resource) because you don't have the database layer up and running. Can you follow the guide in the README to setup supabase locally and you can add that to your environment variables.

With this, registration should go smoothly.

**Comment by olivierlambert** [comment]
I did install/deploy supabase (on another machine where I can run Docker), so it's running and I can reach it. But maybe you have a script somewhere on your own doing something I didn't?

**Comment by olivierlambert** [comment]
So I'm not sure exactly about the configuration between Supabase and Dashboard app. I followed the Supabase self-hosted guide and configured to listen on an IP that can be reach now from the VM running ClassroomIO.

But it's a bit confusing about which service/port I should use.

For example, on Classroom, I have:
* `PUBLIC_SUPABASE_URL` : I don't know which variable it matches on Supabase side. Is it `SUPABASE_PUBLIC_URL` on supabase side?
* `PUBLIC_SUPABASE_BUCKET_URL`: no similar variable on Supabase side.

**Comment by olivierlambert** [comment]
Ah I think I start to understand the issue. Dashboard app is behind an HTTPS frontend (Nginx doing SSL termination) and Supabase is on HTTP. Mixed content is blocked by the browser.

However in HTTPS, I only have self signed certificates for Superbase, and it seems to block the request from Dashboard app.

**Comment by rotimi-best** [comment]
Hi @olivierlambert, will try to answer all your questions.

## Supabase environment variables
1. `PUBLIC_SUPABASE_PROJECT_REF`
![image](https://github.com/rotimi-best/classroomio/assets/31730715/bb4b44c2-1448-4b63-868c-8fab22034008)

2. `PUBLIC_SUPABASE_URL` and `PUBLIC_SUPABASE_ANON_KEY`

![image](https://github.com/rotimi-best/classroomio/assets/31730715/01b816c2-63c5-4795-b5f2-00a518d5762c)

3. `PUBLIC_SUPABASE_BUCKET_URL`: I just realised it isn't used at all so I just created a PR to completely remove it.
https://github.com/rotimi-best/classroomio/pull/129

**Comment by rotimi-best** [comment]
> I wonder if it's possible to tell Dashboard app to ignore self-signed certs.

@olivierlambert I am not sure tbh. I haven't worked with self signed certificates. It seems to me that HTTPS/HTTP issue is a browser constraint and not one that can be controlled from a web app
