### ISSUE TITLE
Move supabase auth from local storage to cookies

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#74]
### Feature Description

Right now we have a local storage based authentication, the tokens are stored in local storage however the problem with this is spinners on the client side to get auth data before using the app.

Cookies based auth would make it faster for a user to see content faster.

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by t-bello7** [comment]
I would like to work on this project. Let's see if .take works

**Comment by rotimi-best** [comment]
.take doesn't seem to work, I tried on a different issue as well

https://github.com/rotimi-best/classroomio/issues/72.

This is a big task though, you will need to understand the following:

1. How supabase auth works pretty well and how cookies work.
2. How to implement it in Sveltekit
3. Change how we make certain API calls.

No 3 isn't of highest priority, until you can make 1 and 2 work well.

**Comment by rotimi-best** [comment]
This link might be helpful: https://github.com/supabase/auth-helpers/tree/main/packages/sveltekit
