### ISSUE TITLE
When I right click on a course card, open a drop down showing several options

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#80]
### Feature Description

When I right click on a card, ONLY on the Dashboard, show the following options:

1. Clone
2. Share
3. Delete
4. Invite

<img width="1303" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/18120c03-c88c-4352-9bd9-0ee5b8b47a9e">

For the UI behavior, use this component: https://carbon-components-svelte.onrender.com/components/ContextMenu

https://github.com/rotimi-best/classroomio/assets/31730715/32d5b627-dd44-4938-ae43-3c0a0a508a7a

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by tioluwani94** [comment]
Hi @rotimi-best I'd like to work on this.

**Comment by rotimi-best** [comment]
Hi, @tioluwani94, sure please go for it 😀.

Please let me know in our discord if you face any blockers https://dub.sh/ciodiscord
