### ISSUE TITLE
[design] Implement Favourite Courses Feature

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#81]
### Feature Description

User should be able to mark a course as favourite and it should be shown on the home page

<img width="1258" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/692b6543-2fe1-49a0-bce3-dbcef43bfd4d">

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by R3mee** [comment]
![Desktop - 1](https://github.com/rotimi-best/classroomio/assets/140942744/f30f1c1a-6717-4993-8619-b06f83b52150)

Title: "Proposal: Add a favorites feature"

The Issue: Users have trouble finding and accessing their favorite courses on the platform. This makes it difficult for them to continue learning and engaging with the platform.

The solution: Adding a favorites feature will allow users to easily find and access their favorite courses. This will improve the user experience and increase engagement with the platform.

- Design details: The favorites feature will be accessible from the main navigation bar, and will include a list of the user's favorite courses. Each course will have a "favorite" button, which will add it to the list. The list will also include the name of the course, the date it was last accessed, the progress, the lessons, the duration. The user will be able to sort the list by date added or date last accessed. The design will use a simple, clean layout that is easy to understand and use.

**Comment by R3mee** [comment]
![Desktop - 3](https://github.com/rotimi-best/classroomio/assets/140942744/a6fe1bfe-a796-46b5-95de-30c763f330bd)
Title: "Proposal: Add a favorites feature"

The Issue: Users have trouble finding and accessing their favorite courses on the platform. This makes it difficult for them to continue learning and engaging with the platform.

The solution: The solution is to add a favorites feature that is inspired by similar features in Figma. The feature will be accessible from the main navigation bar and will include a list of the user's favorite courses. Each course will have a "favorite" button that adds it to the list. The list will also include the name of the course, the date it was last accessed, the progress, the lessons, the duration, and a sorting option by date added or date last accessed. The design will be simple and clean, and will be consistent with the overall design .
