### ISSUE TITLE
[design] Redesign Exercise list page

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#83]
### Feature Description

It should show the following info:

1. Title
2. Deadline

Only for Teachers show:
4. Total Students Submitted,
5. Total students pending

Only for students show:
6. The status of the exercise, graded or in progress

<img width="1274" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/0700d3f4-8d70-49de-8bab-1d44f84b5443">

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by R3mee** [comment]
The Problem: 
The exercise list page is difficult to use and doesn't provide all the necessary information.

The Proposed Solution:
The proposed solution is to create a new exercise list page that is easy to use and provides all the necessary information in a clear and organized way. It would be responsive and would work on all devices. The page would be laid out in a grid, with consistent colors and typography throughout. It would include progress bars, sorting options, a search bar, and clear labels and icons. It would also use a logical hierarchy of information to make it easy for users to find what they're looking for.

The Alternative:
The Alternative is to keep the current exercise list page and add a few new features to make it more user-friendly. These features could include a progress bar, a search bar, and sorting options.

Additional context:
The platform is used by a wide range of users, including students, teachers, and administrators. Each of these user groups has different needs and uses the platform in different ways. For example, teachers need to be able to track their students progress and monitor their performance. Administrators need to be able to manage the platform and make sure it's running smoothly. It's important to keep all of these different users in mind when designing the exercise list page.

Design Details:
The design details, I will suggest using a table or a card-based layout to organize the information. I'd also recommend using icons and color-coding to make the information easier to scan and understand and it should be responsive.
