### ISSUE TITLE
Exercise Date Discrepancy

### ISSUE THREAD

**Issue by Gloriean** [rotimi-best/classroomio#87]
### Issue Description

There is a discrepancy where the exercise date does not correspond with today's date as expected.
The exercise date not matching today's date may cause confusion for users.

[today's_bug.webm](https://github.com/rotimi-best/classroomio/assets/99972504/1a1b9b7c-3b1c-498d-b870-1631bcdd145a)

### Steps to Reproduce

Log in to your dashboard by clicking and entering your credentials in the email and password fields.
Navigate to the "Courses" feature on your dashboard.
Choose a specific course from your created list.
Select the "Lessons" feature.
Navigate to the exercise section 
Observe the exercise date displayed.

### Expected Behavior

The exercise date should correspond with today's date.

### Current Behavior

The exercise date is displaying a date that does not align with today's date.

### Screenshots (optional)

[today's_bug.webm](https://github.com/rotimi-best/classroomio/assets/99972504/10b99f7f-f012-406f-adec-b71eba9e9f65)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rotimi-best** [comment]
Nice catch @Gloriean, thank you.

There is also another bug, there 😃. I noticed you were have lessons without labels and exercise title as well.

Can you create another issues for this? you shouldn't be allowed to. 

Thank you 🙏

**Comment by rotimi-best** [comment]
Fixed by https://github.com/rotimi-best/classroomio/pull/93
