### ISSUE TITLE
Duplicate Invite Issue

### ISSUE THREAD

**Issue by Gloriean** [rotimi-best/classroomio#88]
### Issue Description

After sending an invite to a specific user, attempting to send another invite using the same credentials does not return the expected error message indicating that the user already exists. The system shows the duplicate user details, and even after the user has accepted the invite, the system can still regenerate a new invite.

<img width="1672" alt="Screenshot 2023-12-08 at 16 34 54" src="https://github.com/rotimi-best/classroomio/assets/99972504/87822a66-f849-412d-bf50-0f1466adf934">

### Steps to Reproduce

Log in to the application.
Navigate to the "Settings" feature.
Navigate to the invite section.
Send an invite to a specific user by entering their email address.
Attempt to send another invite to the same user with the same credentials.

### Expected Behavior

An error message should be displayed, indicating that the user already exists and preventing the duplicate invite.
The absence of the error message may lead to confusion and potential duplicate user entries.

### Current Behavior

No error message is shown, and the application allows the sending of a duplicate invite using the same credentials.

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by R4Rohit23** [comment]
@rotimi-best I would like to work on this issue.

**Comment by rotimi-best** [comment]
@R4Rohit23 Sure, thanks. Assigning it to you.
