### ISSUE TITLE
Automatic Saving of Duplicate Organizations After Accepting Invites

### ISSUE THREAD

**Issue by Gloriean** [rotimi-best/classroomio#89]
### Issue Description

Upon accepting duplicate invites, the system automatically saves the same organization, resulting in potential data duplication.

<img width="1679" alt="Screenshot 2023-12-08 at 16 45 22" src="https://github.com/rotimi-best/classroomio/assets/99972504/4cea5916-a02a-4bd9-bcda-fc08944f5984">

### Steps to Reproduce

1. Log in to the application.
2. Accept an invite to join an organization.
3. Accept another duplicate invite to join the same organization.

### Expected Behavior

The system should prevent the automatic saving of duplicate organizations and provide an error message indicating the existing organization. The automatic saving of duplicate organizations can lead to data inconsistency and confusion.

### Current Behavior

The system saves the duplicate organization automatically without providing an error message.

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rotimi-best** [comment]
@Gloriean I think this will be fixed by preventing you from sending multiple invites to the same person, the issue we discussed about on discord.

I'll be closing it for now, if the issue happens after that fix, I will reopen it again.
