### ISSUE TITLE
Duplicate Response Messages

### ISSUE THREAD

**Issue by Gloriean** [rotimi-best/classroomio#90]
### Issue Description

The application displays duplicate response messages in certain scenarios, causing redundancy in user feedback.

<img width="1277" alt="Screenshot 2023-12-08 at 16 25 59" src="https://github.com/rotimi-best/classroomio/assets/99972504/f187da16-9957-4210-8e65-2146f0473fa5">

### Steps to Reproduce

1. Trigger a specific action that generates a response message.
2. Observe the displayed response message.

### Expected Behavior

The application should display a single, non-duplicate response message for the triggered action. Duplicate response messages can confuse users and may indicate a possible logic error.

### Current Behavior

Duplicate response messages are shown, leading to redundancy in user feedback.

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rotimi-best** [comment]
@Gloriean Thanks for reporting this issue.

I also noticed another bug here, a user should not be allowed to invite an email that is already in the list of invites
![image](https://github.com/rotimi-best/classroomio/assets/31730715/4fb73578-a0c5-4804-8f35-8f66cbbe745f)
