### ISSUE TITLE
Unsuccessful Invite Sending

### ISSUE THREAD

**Issue by Gloriean** [rotimi-best/classroomio#97]
### Issue Description

Sending an invite to a user is not successful, and the expected outcome of successfully inviting a user is not achieved.

[Monday's bug.webm](https://github.com/rotimi-best/classroomio/assets/99972504/1abcdb65-eed0-40e6-8e01-d866e4d42721)
[Second_bug.webm](https://github.com/rotimi-best/classroomio/assets/99972504/bb5421f1-be43-4944-a524-4157f35a521e)

### Steps to Reproduce

1. Log in to the application.
2. Navigate to the "Settings" feature.
3. Select the "Organization" Feature.
4. Choose the "Team" field. 
5. Click the "Manage Team" button
6. Navigate to the invite section.
7. Attempt to send an invite to a specific user by entering their email address.

### Expected Behavior

The system should successfully send the invite, and the user should receive an invitation.

### Current Behavior

Sending the invite is not successful, and the user does not receive an invitation. No confirmation or error message is provided.

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rotimi-best** [comment]
@Gloriean this fix has now been merged. Thanks for catching it.

Please can you reconfirm

**Comment by Gloriean** [comment]
It's been fixed!
