### ISSUE TITLE
Verify if email is disposable before signup

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#99]
### Feature Description

Use the service built by @dephraiim to verify the email because we allow the user sign up.

https://github.com/dephraiim/disposable-email-api

### Use Case

We need to prevent people from using disposable emails to signup to classroomio.

### Proposed Solution

- Read the docs of Duncans API
- Before we send the email of the user to supabase, call that API to verify it is not disposable
- If disposable, show an error saying "Email is disposable"
- else continue the signup flow

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Dun-sin** [comment]
hi @rotimi-best can i take this?

**Comment by rotimi-best** [comment]
Hi @Dun-sin thank you for volunteering to pick this 😊.

However @topboyasante is working on this. I should've assigned to him for visibility

**Comment by Dun-sin** [comment]
> Hi @Dun-sin thank you for volunteering to pick this 😊.
> 
> However @topboyasante is working on this. I should've assigned to him for visibility

got it

**Comment by topboyasante** [comment]
Picking this up.

**Comment by rotimi-best** [comment]
@Dun-sin will you be interested in checking this issue out https://github.com/rotimi-best/classroomio/issues/114 instead?

**Comment by Dun-sin** [comment]
> @Dun-sin will you be interested in checking this issue out https://github.com/rotimi-best/classroomio/issues/114 instead?

Alright, will like to take that
